version: '3'

services:
  app:
    image: url-shortener-auth:local
    container_name: url-shortener-auth-app
    environment:
      HTTP_PORT: 8003
    ports:
      - "8003:8003"
    depends_on:
      - goose

  postgres:
    image: postgres:14-alpine
    container_name: url-shortener-auth-psql
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=url-shortener-auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  goose:
    image: artsafin/goose-migrations:latest
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/db/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://postgres:${DB_PASSWORD}@postgres:5432/url-shortener-auth-db?sslmode=disable"
    command: ["-dir", "/db/migrations", "up"]