http:
  timeouts:
    read-ms: 10000
    write-ms: 10000
    read-header-ms: 10000
    idle-ms: 10000

db:
  host: "postgres"
  port: 5432
  username: "postgres"
  db-name: "email-auth-db"
  ssl-mode: "disable"

email:
  host: "smtp.gmail.com"
  port: 587
  sender-email: "code.dev256@gmail.com"